site_name: CRIPT Documentation
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
    logo: img/logo.png
markdown_extensions:
- toc:
    baselevel: 1
    toc_depth: 3
    permalink: True
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.caret
- pymdownx.tilde

repo_url: https://criptapp.herokuapp.com/index/
repo_name: CRIPT App


nav:
    - Home:
          README.md
    - Data Schema:
        - data-models/README.md
        - Challenges of Polymer Data: data-models/Polymers.md
        - Data Model Explained: data-models/Data_Entry.md
        - Users: data-models/Users.md
        - Groups: data-models/Groups.md
        - Publications: data-models/Publications.md
        - Collections: data-models/Collections.md
        - Experiments: data-models/Experiments.md
        - Materials - polymers: data-models/Materials_P.md
        - Materials - other: data-models/Materials_O.md
        - Process: data-models/Process.md
        - Simulation: data-models/Simulation.md
        - Sample: data-models/Sample.md
        - Data: data-models/Data.md
        - Model Lake: data-models/Model_lake.md
        - Data Lake: data-models/Data_Lake.md
        - Version Control: data-models/Version_Control.md
        - Example: data-models/Example.md
        - FAQ: data-models/FAQ.md
    - Software Tools:
        - software-tools/README.md
    - Web Application:
        - web-application/README.md
    - About:
        - about/README.md

extra_css:
  - stylesheets/extra.css