site_name: CRIPT Documentation
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
    logo: img/logo.png
markdown_extensions:
- toc:
    baselevel: 1
    toc_depth: 3
    permalink: True
- pymdownx.highlight
- pymdownx.superfences

repo_url:

nav:
    - Home:
          README.md
    - Data Models:
        - data-models/README.md
        - Groups: data-models/Groups.md
        - Users: data-models/Users.md
        - Publications: data-models/Publications.md
        - Experiments: data-models/Experiments.md
        - Materials - polymers: data-models/Materials_P.md
        - Materials - other: data-models/Materials_O.md
        - Process: data-models/Process.md
        - Data: data-models/Data.md
        - Modules: data-models/Modules.md
        - Issues: data-models/Issues.md
    - Software Tools:
        - software-tools/README.md
    - Web Application:
        - web-application/README.md

extra_css:
  - stylesheets/extra.css